airdnc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.views.static import serve

from accounts import urls as urls_accounts
from home import urls as urls_home
from cart import urls as urls_cart
from checkout import urls as urls_checkout
from products import urls as urls_products
from userprofile import urls as urls_userprofile
from products.views import all_products
from projects.views import index

from .settings import MEDIA_ROOT

urlpatterns = [
    # if user goes to admin/, load admin app
    url(r'^$', include(urls_home)),
    # if user goes to admin/, load admin app
    url(r'^admin/', admin.site.urls),
    # if user goes to root/index, redirect to projects/
    # url(r'^$', index, name='index'),
    # if user goes to accounts/, parse url in urls.py i accounts app
    url(r'^accounts/', include(urls_accounts)),
    # if user goes to projects/, parse url in urls.py in projects app
    url(r'projects/', include('projects.urls')),
    # Tinymce
    url(r'^tinymce/', include('tinymce.urls')),
    # Products
    url(r'^products/', include(urls_products, namespace="products")),
    # Social auth URLS
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # Cart
    url(r'^cart/', include(urls_cart)),
    # Checkout
    url(r'^checkout/', include(urls_checkout)),
    # Profile
    url(r'^profile/', include(urls_userprofile)),
    # if user goes to media/, use RegEx to point to a path of a file
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

cart/urls.py
from django.conf.urls import url
from .views import view_cart, add_to_cart, adjust_cart

urlpatterns = [
    url(r'^$', view_cart, name='view_cart'),
    url(r'^add/(?P<id>\d+)', add_to_cart, name='add_to_cart'),
    url(r'^adjust/(?P<id>\d+)', adjust_cart, name='adjust_cart'),
]

products/urls.py
from django.conf.urls import url, include
from .views import all_products


urlpatterns = [
    url(r'^$', all_products, name='products'),
    ]

userprofile/urls.py
from django.conf.urls import url
from .views import update_profile

urlpatterns = [
    url(r'^update/$', update_profile, name='update_profile'),
    ]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    premium = models.BooleanField(default=False)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

# Create your models here.

userprofile/forms.py
from django import forms
from .models import User, Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')
        help_texts = {
            'username': None,
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ()

userprofile/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import UserForm, ProfileForm
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render
from projects.views import index
from .models import Profile
from projects.models import Projects, Category
from django.db.models import Q
import sweetify

# Create your views here.


@login_required
@transaction.atomic
def update_profile(request):
    categories = Category.objects.filter(user__exact=request.user)
    projects = Projects.objects.filter(user__exact=request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, (
                'Your profile was successfully updated!'))
            sweetify.success(
                request, 'Your profile has been updated', timer=2000, toast=True)
            return redirect(update_profile)
        else:
            messages.error(request, ('Please correct the error below.'))
            sweetify.error(
                request, 'Please correct the error below.', timer=2000, toast=True)
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    premium = Profile.objects.filter(
        Q(premium=True)).filter(user__exact=request.user)
    if premium:
        return render(request, 'userprofile.html', {
            'user_form': user_form,
            'profile_form': profile_form,
            'profile': premium,
            'projects': projects,
            'categories': categories
        })
    else:
        return render(request, 'userprofile.html', {
            'user_form': user_form,
            'profile_form': profile_form,
            'projects': projects,
            'categories': categories
        })

userprofile/templates/userprofile.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% block content %}
<div class="col-lg-12">
  <div class="row offset-lg-3 col-lg-6">
    <div class="offset-lg-2 col-lg-6">
      <span class="alignleft">
        <h4>Edit profile</h4>
      </span>
      <span class="alignright">
        {% if profile %}
        <a role="button" class="btn btn-outline-success" data-toggle="tooltip" data-placement="bottom" title="You are on the premium plan!">
          Premium
        </a>
        {% else %}
        <a role="button" class="btn btn-outline-info" href="{% url 'products:products' %}" data-toggle="tooltip" data-placement="bottom" title="You are on the free plan!">
          <i class="fa fa-star-o"></i> Upgrade
        </a>
        {% endif %}
      </span>
    </div>
    <hr>
    <div class="offset-lg-3 col-lg-6">
      <div class="row">
        <form method="post">
          {% csrf_token %}
          {{ user_form | as_bootstrap }}
          {{ profile_form | as_bootstrap }}
          <div>
            <span class="alignleft">
              <button class="btn btn-success" type="submit">Save</button>
            </span>
          </div>
          <div>
            <span class="alignright">
              <a class="btn btn-warning" href="{% url 'logout' %}">Logout</a>
            </span>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}